GET {{HOST}}:{{PORT}}/hello-world

###
GET {{HOST}}:{{PORT}}/hello-world-bean

###
GET {{HOST}}:{{PORT}}/hello-world/path-variable/Van

### Internationalization - i18n
GET {{HOST}}:{{PORT}}/hello-world_internationalized
Accept-Language: hu