POST {{HOST}}:{{PORT}}/users
Content-Type: application/json

{
  "id": 0,
  "name": "u",
  "birthDate": "5998-09-25"
}

###
GET {{HOST}}:{{PORT}}/users

###
GET {{HOST}}:{{PORT}}/users/404


###
DELETE {{HOST}}:{{PORT}}/users/1